# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run stubber

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout stubbber Repo
      uses: actions/checkout@v2
      with:
        repository: josverl/micropython-stubber
        path: worker

    - name: Checkout micropython
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        path: temp/stubber

    - name: Checkout micropython-lib
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython-lib
        submodules: recursive  
        path: temp/micropython-lib


    - name: Checkout stubbber Repo
      uses: actions/checkout@v2
      with:
        repository: josverl/micropython-stubber
        path: temp/micropython-lib


    - name: Checkout Stubs Repo
      uses: actions/checkout@v2
      with:
        repository: josverl/micropython-stubs
        path: stubs

        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
  
    - name: Install repo dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # - name: Test with pytest
      #   run: |
      #     pytest

    - name: run stubber
      run: |
        python main.py
        

    - uses: gr2m/create-or-update-pull-request-action@v1.x
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"        

