# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: minify-RP

on:
  workflow_dispatch:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: run `process minify`
      run: |
        python process.py minify

    ## Needs Secrets.PAT 
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: add/update minified
        labels: |
          automated pr

        # # token: ${{ secrets.PAT }}
        # committer: GitHub <noreply@github.com>
        # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        # signoff: false
        # branch: minified
        # delete-branch: true
        # title: '[Example] Update report'
        # body: |
        #   minified
        #   - Updated with *today's* date


    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"




