# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: minify-RP

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: run `process minify`
      run: |
        python process.py minify

    - name: verify minified using pylint
      run: |
        pylint minified/createstubs.py -E -d E0401,E1101
        # ignore Unable to import '<upythonmodule>' (import-error)
        # ignore Module 'gc' has no 'mem_free' member (no-member)

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      # ref: https://github.com/peter-evans/create-pull-request
      with:
        branch: minify-${{ steps.extract_branch.outputs.branch }}
        commit-message: add/update minified
        labels: |
          automated pr
        title: '${{ steps.extract_branch.outputs.branch }} : update minified/createstubs.py'
        body: |
           - Updated with *today's* date        

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"




